### ISSUE TITLE
Testkube operator's cronjob template labels/annotations cannot be modified

### ISSUE THREAD

**Issue by michal-jagiello-tmpl** [kubeshop/helm-charts#607]
**Is your feature request related to a problem? Please describe.**
We are using testkube on a cluster where service mesh is enabled. On each pod there is an istio-proxy container added. Currently there is no option to disable creation of istio-proxy on cronjob (without editing cronjob template and releasing new helm chart) based on some flag on values by adding specific label into it's template.

**Describe the solution you'd like**
I'd like to modify cronjob's template labels based on a value on helm chart

**Describe alternatives you've considered**
If we would be able to overwrite cronjob somehow (from helm chart level, not editing operator deploment) so our own cronjob template could be used -- that can be also a solution

**Comment by vsukhin** [comment]
hey, @michal-jagiello-tmpl 
1. you can adjust cronjob-template for your tests, we already did for one of the user requests  http://docs.testkube.io/articles/creating-tests#changing-the-default-cronjob-template-used-for-scheduled-test-execution
2. Cron job template is a sttatic asset containing golang template, so we moved it out Helm chart templates, because they are same golang tempaltes :) Might be @ypoplavs has some ideas how to achieve it

**Comment by michal-jagiello-tmpl** [comment]
Thanks @vsukhin
Ad.1 I can see you can use that for a test, is it possible for testsuite as well?

**Comment by vsukhin** [comment]
yes, for both test and test suite

**Comment by michal-jagiello-tmpl** [comment]
ok, tested and works. thanks @vsukhin 
Can be closed then
